DROP TABLE IF EXISTS stories CASCADE;
CREATE TABLE stories (
  id SERIAL PRIMARY KEY NOT NULL,
  author_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  chapter_id INTEGER REFERENCES chapters(id) ON DELETE CASCADE,
  story_title VARCHAR(127) NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(30) NOT NULL,
  genre VARCHAR(30) NOT NULL,
  age_rating VARCHAR(7) NOT NULL,
  date_created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  completed BOOLEAN DEFAULT FALSE
);
