DROP TABLE IF EXISTS winners CASCADE;
CREATE TABLE winners (
  id SERIAL PRIMARY KEY NOT NULL,
  story_id INTEGER REFERENCES stories(id) ON DELETE CASCADE,
  parent_id INTEGER REFERENCES contributions(id) DEFAULT NULL ON DELETE CASCADE,
  child_id INTEGER REFERENCES contributions(id) ON DELETE CASCADE
);
